DjangoBiblioteca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('cuentas/', include('django.contrib.auth.urls')),
]

books/urls.py
from books import views

from django.urls import path

app_name = 'books'
urlpatterns = [

        path("", views.booklist, name='booklist'),
        path("<int:book_id>", views.bookdetails, name='bookdetails'),
        path("autores/", views.authorlist, name='authorlist'),
        path("autores/<int:author_id>", views.authordetails, name='authordetails'),
        path("genres/", views.genrelist, name='genrelist'),

]

django_library/urls.py
from django.contrib import admin
from django.urls import path, include

from books import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

books/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField(blank=True, null= False)

    def __str__(self):
        return self.first_name

class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    publish_date = models.DateField()
    summary = models.TextField()

    def __str__(self):
        return self.title

    def was_published_recently(self):
        return self.publish_date >= timezone.now() - datetime.timedelta(days=1)

books/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from books.models import Book, Author, Genre


# Create your views here.

@login_required
def booklist(request):
    latest_books = Book.objects.order_by('-publish_date')[:5]
    return render(request, template_name= "book_list.html", context={"latest_books":latest_books})

def bookdetails(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, template_name= "book_details.html", context={"book":book})

@login_required
def authorlist(request):
    latest_authors = Author.objects.order_by('-birth_date')[:5]
    return render(request, template_name="author_list.html", context={"latest_authors":latest_authors})


@login_required
def authordetails(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, template_name="author_details.html", context={"author":author})

@login_required
def genrelist(request):
    latest_genres = Genre.objects.all()
    return render(request, template_name="genre_list.html", context={"latest_genres":latest_genres})

books/templates/author_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalles de autor</title>
</head>
<body>
    <h1 style="font-family: 'DejaVu Sans Mono'">Autores del momento</h1>
    <h2 style="font-family: cursive">{{ author.first_name }} {{ author.last_name }}</h2>

    <ul style="list-style-type: square">
        <li><strong>Nombre del autor</strong>: {{ author.first_name }}</li>
        <li><strong>Apellido del autor</strong>: {{ author.last_name}}</li>
        <li><strong>Fecha de nacimiento</strong>: {{ author.birth_date }}</li>
    </ul>

</body>
</html>

books/templates/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de autores</title>
</head>
<body>

    {% if latest_authors %}
        <ul>
            {% for author in latest_authors %}
                <li><a href="{% url 'books:authordetails' author.id %}"> {{ author.first_name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Sorry, there aren´t any available authors at the moment!</h2>
    {% endif %}

    <h3>Link to our <a href="{% url 'books:booklist' %}">book list</a></h3>
    <h3>Link to our <a href="{% url 'books:genrelist' %}"> genre list</a></h3>

</body>
</html>

books/templates/book_details.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalles de libro</title>
</head>
<body>
    <h1 style="font-family: 'DejaVu Sans Mono'">Libros del momento</h1>
    <h2 style="font-family: cursive">{{ book.title }}, escrito por {{ book.author }}</h2>


    <h3 style="font-family: Hack">Características del libro:</h3>
    <ul style="list-style-type: square">
        <li><strong>Nombre del libro</strong>: {{ book.title }}</li>
        <li><strong>Nombre del autor</strong>: <a href="{% url 'books:authordetails' book.id %}">{{ book.author }}</a></li>
        <li><strong>Género del libro</strong>: {{ book.genre }}</li>
        <li><strong>Fecha de publicación</strong>: {{ book.publish_date }}</li>
        <li><strong>Sinopsis</strong>: {{ book.summary }}</li>
    </ul>

    <form method="post" action="{% url 'logout' %}" style="margin-top: 20px;">
        {% csrf_token %}
        <button type="submit">
            Cerrar sesión
        </button>
    </form>

</body>
</html>

books/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de libros</title>
</head>
<body>

    {% if latest_books %}
        <ul>
            {% for book in latest_books %}
                <li><a href="{% url 'books:bookdetails' book.id %}"> {{ book.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Sorry, there aren´t any available authors at the moment!</h2>
    {% endif %}

    <h3>Link to our <a href="{% url 'books:authorlist' %}">author list</a></h3>
    <h3>Link to our <a href="{% url 'books:genrelist' %}"> genre list</a></h3>

</body>
</html>

books/templates/books/author_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

books/templates/books/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author list</title>
</head>
<body>

    {% if latest_authors %}
        <ul>
            {% for author in latest_authors %}
                <li><a href="{% url 'books:author_detail' %}"></a> {{ author.author_text }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Sorry, there aren´t any available authors at the moment</h2>
    {% endif %}

</body>
</html>

books/templates/books/book_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

books/templates/books/books_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

books/templates/formualario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inicio de sesión</title>
</head>
<body>

  <h1 style="text-decoration: underline">Formulario de inicio de sesión</h1>

  <form method="post">
    {% csrf_token %}
    <label for="usuario">Usuario: </label>
    <input type="text" name="usuario" id="usuario">
    <br>
    <label for="contrasena">Contraseña: </label>
    <input type="password" name="contrasena" id="contrasena">
    <button type="submit">Iniciar sesión</button>
  </form>

</body>
</html>

books/templates/formulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inicio de sesión</title>
</head>
<body>

  <h1 style="text-decoration: underline">Formulario de inicio de sesión</h1>

  <form method="post">
    {% csrf_token %}
    <label for="usuario">Usuario: </label>
    <input type="text" name="usuario" id="usuario">
    <br>
    <label for="contrasena">Contraseña: </label>
    <input type="password" name="contrasena" id="contrasena">
    <button type="submit">Iniciar sesión</button>
  </form>

</body>
</html>

books/templates/genre_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de géneros</title>
</head>
<body>

        {% if latest_genres %}
        <ul>
            {% for genre in latest_genres %}
                <li>{{ genre.name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Sorry, there aren´t any available genres at the moment!</h2>
    {% endif %}

    <h3>Link to our <a href="{% url 'books:booklist' %}">book list</a></h3>
    <h3>Link to our <a href="{% url 'books:authorlist' %}">author list</a></h3>



</body>
</html>